site_name: Aviation

theme:
  name: material

nav:
  - Home: "index.md"
  - Aviation Model: "aviation.md"

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
