site_name: Aviation

theme:
  name: material

plugins:
  - search
  - bibtex:
      bib_file: "https://api.zotero.org/groups/5782724/collections/G847TDER/items?format=bibtex"
  - mkdocs-prebuild:
      base_path: ["."]
nav:
  - Home: "index.md"
  - Aviation Model: "fleet.md"

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - ../javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - attr_list
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
